// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsrvsrnxjxvugmqzemav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzcnZzcm54anh2dWdtcXplbWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDI0MzcsImV4cCI6MjA2NjU3ODQzN30.JEuxybNvuEQgDBS-28ZEtcgnuPQIDqIWZ_NdnnA4VWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);